version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - .:/home/node/api
    #   - /home/node/api/node_modules
    depends_on:
      - database
    ports:
      - '3000:3000'
    depends_on: 
      - database
    # networks:
    #   - app-tier  
    # network_mode: "service:database"
    # environment:
    #   - DB_HOST=database
    #   - DB_USER=root
    #   - DB_PASSWORD=password
    #   - DB_NAME=Ticket
    #   - DB_PORT=3306
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ticket
    ports:
      - "3306:3306"
    # expose:
    #   - "3306"  
    hostname: database
    # networks:
    #   - app-tier  

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    external_links:
      - ticket-management_database_1:mysql

